//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ARAF_OPERATOR_PANEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ARF_PRODUCTION_OPERATOR
    {
        public int PRD_OPR_ID { get; set; }
        public Nullable<int> PROD_ID { get; set; }
        public Nullable<int> OPR_ID { get; set; }
        public Nullable<int> ROT_ID { get; set; }
        public Nullable<int> PRD_WS_ID { get; set; }
        public Nullable<int> PRD_STATUS { get; set; }
        public string OPR_BARCODE { get; set; }
        public string OPR_NAME { get; set; }
        public Nullable<int> OPR_STATUS { get; set; }
        public Nullable<System.DateTime> PROD_START_DATE { get; set; }
        public Nullable<System.DateTime> PROD_END_DATE { get; set; }
        public Nullable<double> PROD_QUANTITY { get; set; }
        public Nullable<double> REPORT_QUANTITY { get; set; }
        public Nullable<int> WSG_ID { get; set; }
        public string WS_CODE { get; set; }
        public string WS_NAME { get; set; }
        public string COMPUTER_NAME { get; set; }
        public Nullable<int> WS_ID { get; set; }
    }
}
