//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ARAF_OPERATOR_PANEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ARF_SYSTEM_USERS
    {
        public int USER_ID { get; set; }
        public string USER_CODE { get; set; }
        public string USER_PASS { get; set; }
        public string USER_NAME { get; set; }
        public string USER_EMAIL { get; set; }
        public Nullable<bool> USER_STATUS { get; set; }
        public Nullable<int> USER_GRUPID { get; set; }
        public string SURNAME { get; set; }
        public string NAME { get; set; }
        public Nullable<int> SYSUSER_GRUPID { get; set; }
        public string SYSUSERGRP_NAME { get; set; }
    }
}
