//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ARAF_OPERATOR_PANEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ARF_OPERATOR_PANEL
    {
        public int PROD_PLAN_ID { get; set; }
        public Nullable<int> PROD_ID { get; set; }
        public Nullable<int> PLAN_ID { get; set; }
        public Nullable<int> WS_ID { get; set; }
        public Nullable<int> PRD_PLN_QUANTITY { get; set; }
        public Nullable<int> MULTIPLIER { get; set; }
        public Nullable<int> DIVIDING { get; set; }
        public Nullable<int> PROD_PLAN_STATUS { get; set; }
        public Nullable<System.DateTime> PROD_PLAN_START_DATE { get; set; }
        public Nullable<System.DateTime> PROD_PLAN_END_DATE { get; set; }
        public Nullable<int> OP_ID { get; set; }
        public string OP_NAME { get; set; }
        public Nullable<System.DateTime> PLAN_DATE { get; set; }
        public Nullable<System.DateTime> PLAN_START_TIME { get; set; }
        public Nullable<System.DateTime> PLAN_END_TIME { get; set; }
        public string WORK_ORDER_NO { get; set; }
        public Nullable<int> PLAN_STATUS { get; set; }
        public Nullable<int> ITEM_ID { get; set; }
        public string ITEM_CODE { get; set; }
        public string ITEM_NAME { get; set; }
        public string CUSTOMER_CODE { get; set; }
        public string CUSTOMER_NAME { get; set; }
        public Nullable<double> WORK_ORDER_QUANTITY { get; set; }
        public Nullable<int> ERP_ID { get; set; }
        public Nullable<double> AMOUNT { get; set; }
        public Nullable<System.DateTime> ORDER_DATE { get; set; }
        public Nullable<System.DateTime> DELIVERY_DATE { get; set; }
        public string LINEEXP { get; set; }
        public Nullable<int> WSG_ID { get; set; }
        public string WS_CODE { get; set; }
        public string WS_NAME { get; set; }
        public string COMPUTER_NAME { get; set; }
        public Nullable<System.DateTime> PROD_START_DATE { get; set; }
        public Nullable<System.DateTime> PROD_END_DATE { get; set; }
        public Nullable<double> PROD_QUANTITY { get; set; }
        public Nullable<double> REPORT_QUANTITY { get; set; }
        public Nullable<int> OPR_PIECE { get; set; }
        public Nullable<int> PROD_STATUS { get; set; }
        public string OPR_NAME { get; set; }
        public string SHIFT_CODE { get; set; }
        public Nullable<double> PRODUCTIVITY { get; set; }
        public Nullable<double> REMAINING { get; set; }
        public string PRODUCTION_STATUS { get; set; }
        public int ACTIVE_SUSPEND_TIME { get; set; }
        public int TOTAL_SUSPEND_TIME { get; set; }
        public int SETTING_SUSPEND_TIME { get; set; }
        public Nullable<int> TOTAL_TIME { get; set; }
        public Nullable<int> NET_TIME { get; set; }
        public string COLOR { get; set; }
        public int SUSPEND_ID { get; set; }
    }
}
