//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ARAF_OPERATOR_PANEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ARF_PRODUCTION_SUSPEND
    {
        public Nullable<int> SUSPEND_TIME { get; set; }
        public int SUSPEND_ID { get; set; }
        public int PROD_ID { get; set; }
        public Nullable<int> OPR_ID { get; set; }
        public string COMMENT { get; set; }
        public string SUSPEND_NAME { get; set; }
        public string SUSPEND_TYPE { get; set; }
    }
}
