//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ARAF_OPERATOR_PANEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ARF_ITEM_OPERATIONS
    {
        public int ITEM_OP_ID { get; set; }
        public int QUEUE { get; set; }
        public int ITEM_ID { get; set; }
        public int OP_ID { get; set; }
        public Nullable<double> OP_TIME_UNIT { get; set; }
        public int WS_ID { get; set; }
        public bool LAST_OP { get; set; }
        public string ITEM_CODE { get; set; }
        public string ITEM_NAME { get; set; }
        public Nullable<int> UNIT { get; set; }
        public Nullable<double> STATUS { get; set; }
        public string TYPE { get; set; }
        public Nullable<int> ERP_ID { get; set; }
        public Nullable<int> ITEM_GRP_ID { get; set; }
        public string OP_CODE { get; set; }
        public string OP_NAME { get; set; }
        public Nullable<int> WSG_ID { get; set; }
        public string WS_CODE { get; set; }
        public string WS_NAME { get; set; }
    }
}
