//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ARAF_OPERATOR_PANEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ARF_W_ITEM_TREE
    {
        public int ITEM_TREE_ID { get; set; }
        public int ITEM_ID { get; set; }
        public string ITEM_CODE { get; set; }
        public string ITEM_NAME { get; set; }
        public int MATERIAL_ID { get; set; }
        public string MATERIAL_CODE { get; set; }
        public string MATERIAL_NAME { get; set; }
        public decimal AMOUNT { get; set; }
        public int ORDER { get; set; }
    }
}
