//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ARAF_OPERATOR_PANEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ARF_W_COUNTER_DETAIL
    {
        public int WSD_ID { get; set; }
        public string WS_CODE { get; set; }
        public string WS_NAME { get; set; }
        public string PLC_DT { get; set; }
        public Nullable<int> WSD_COUNTER { get; set; }
    }
}
