//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ARAF_OPERATOR_PANEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ARF_SUSPEND_WORKSTATION
    {
        public int SSPND_WS_ID { get; set; }
        public Nullable<int> SUSPEND_ID { get; set; }
        public Nullable<int> WS_ID { get; set; }
        public Nullable<int> BUTTON_QUEUE { get; set; }
        public string SUSPEND_NAME { get; set; }
        public Nullable<int> SUSPEND_GROUP_ID { get; set; }
        public string SUSPEND_TYPE { get; set; }
        public Nullable<int> WSG_ID { get; set; }
        public string WS_CODE { get; set; }
        public string WS_NAME { get; set; }
        public string COMPUTER_NAME { get; set; }
    }
}
