//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ARAF_OPERATOR_PANEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ARF_PLANNING_STATUS
    {
        public string PLAN_STATUS { get; set; }
        public int ITEM_ID { get; set; }
        public string ITEM_CODE { get; set; }
        public string ITEM_NAME { get; set; }
        public Nullable<int> QUEUE { get; set; }
        public Nullable<double> PLAN_AMOUNT { get; set; }
        public Nullable<int> PROD_QUANTITY { get; set; }
        public Nullable<double> KALAN { get; set; }
        public Nullable<int> ITEM_OP_ID { get; set; }
        public Nullable<int> OP_ID { get; set; }
        public Nullable<double> OP_TIME_UNIT { get; set; }
        public Nullable<int> WS_ID { get; set; }
        public Nullable<bool> LAST_OP { get; set; }
        public string OP_CODE { get; set; }
        public string OP_NAME { get; set; }
    }
}
