//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ARAF_OPERATOR_PANEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ARF_ITEMS_LIST
    {
        public int ITEM_ID { get; set; }
        public string ITEM_CODE { get; set; }
        public string UNIT { get; set; }
        public string ITEM_NAME { get; set; }
        public Nullable<double> STATUS { get; set; }
        public Nullable<int> ERP_ID { get; set; }
        public string TYPE { get; set; }
        public Nullable<int> ITEM_GRP_ID { get; set; }
        public string ITEM_GRP_CODE { get; set; }
        public string ITEM_GRP_NAME { get; set; }
        public string UNIT_NAME { get; set; }
        public string EXPLANATION { get; set; }
    }
}
