//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ARAF_OPERATOR_PANEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ITEM_TREE
    {
        public int ITEM_TREE_ID { get; set; }
        public int MUST { get; set; }
        public int ITEM_ID { get; set; }
        public int MATERIAL_ID { get; set; }
        public decimal AMOUNT { get; set; }
    
        public virtual ITEM_TREE ITEM_TREE1 { get; set; }
        public virtual ITEM_TREE ITEM_TREE2 { get; set; }
        public virtual ITEMS ITEMS { get; set; }
        public virtual ITEMS ITEMS1 { get; set; }
    }
}
