//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ARAF_OPERATOR_PANEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class OPERATOR
    {
        public int OPR_ID { get; set; }
        public string OPR_BARCODE { get; set; }
        public string OPR_NAME { get; set; }
        public Nullable<int> OPR_STATUS { get; set; }
    }
}
