//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ARAF_OPERATOR_PANEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PANEL_TYPE_DETAIL
    {
        public int PANEL_TYPE_ID { get; set; }
        public Nullable<int> PANEL_ID { get; set; }
        public string FIELD_NAME { get; set; }
        public string FIELD_CAPTION { get; set; }
        public Nullable<int> QUEUE { get; set; }
        public Nullable<byte> ACTIVE { get; set; }
    }
}
