//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ARAF_OPERATOR_PANEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PLANNING
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PLANNING()
        {
            this.PRODUCTION_PLANNING = new HashSet<PRODUCTION_PLANNING>();
        }
    
        public int PLAN_ID { get; set; }
        public Nullable<int> WS_ID { get; set; }
        public Nullable<int> OP_ID { get; set; }
        public Nullable<System.DateTime> PLAN_DATE { get; set; }
        public Nullable<System.DateTime> PLAN_START_TIME { get; set; }
        public Nullable<System.DateTime> PLAN_END_TIME { get; set; }
        public string WORK_ORDER_NO { get; set; }
        public Nullable<int> PLAN_STATUS { get; set; }
        public int ITEM_ID { get; set; }
        public string CUSTOMER_CODE { get; set; }
        public string CUSTOMER_NAME { get; set; }
        public Nullable<double> WORK_ORDER_QUANTITY { get; set; }
        public Nullable<int> ERP_ID { get; set; }
        public Nullable<double> AMOUNT { get; set; }
        public Nullable<System.DateTime> ORDER_DATE { get; set; }
        public Nullable<System.DateTime> DELIVERY_DATE { get; set; }
        public string LINEEXP { get; set; }
    
        public virtual ITEMS ITEMS { get; set; }
        public virtual OPERATIONS OPERATIONS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PRODUCTION_PLANNING> PRODUCTION_PLANNING { get; set; }
        public virtual WORKSTATION WORKSTATION { get; set; }
    }
}
