//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ARAF_OPERATOR_PANEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PLC
    {
        public int PLC_ID { get; set; }
        public string PLC_IP { get; set; }
        public string PLC_NAME { get; set; }
        public Nullable<bool> PLC_STATUS { get; set; }
        public Nullable<byte> PLC_TYPE { get; set; }
        public Nullable<int> PLC_PORT { get; set; }
    }
}
