//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ARAF_OPERATOR_PANEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUCTION
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PRODUCTION()
        {
            this.PRODUCTION_PLANNING = new HashSet<PRODUCTION_PLANNING>();
            this.PRODUCTION_SUSPEND = new HashSet<PRODUCTION_SUSPEND>();
        }
    
        public int PROD_ID { get; set; }
        public Nullable<System.DateTime> PROD_START_DATE { get; set; }
        public Nullable<System.DateTime> PROD_END_DATE { get; set; }
        public Nullable<double> PROD_QUANTITY { get; set; }
        public Nullable<double> REPORT_QUANTITY { get; set; }
        public Nullable<int> WS_ID { get; set; }
        public Nullable<int> OPR_PIECE { get; set; }
        public Nullable<int> PROD_STATUS { get; set; }
        public Nullable<System.DateTime> LAST_READ_DATE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PRODUCTION_PLANNING> PRODUCTION_PLANNING { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PRODUCTION_SUSPEND> PRODUCTION_SUSPEND { get; set; }
        public virtual WORKSTATION WORKSTATION { get; set; }
    }
}
