//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ARAF_OPERATOR_PANEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUCTION_SUSPEND
    {
        public int PROD_SUSPEND_ID { get; set; }
        public int SUSPEND_ID { get; set; }
        public int PROD_ID { get; set; }
        public Nullable<int> OPR_ID { get; set; }
        public Nullable<System.DateTime> SUSPEND_START_TIME { get; set; }
        public Nullable<System.DateTime> SUSPEND_END_TIME { get; set; }
        public Nullable<byte> SUSPEND_STATUS { get; set; }
        public string COMMENT { get; set; }
    
        public virtual SUSPEND SUSPEND { get; set; }
        public virtual PRODUCTION PRODUCTION { get; set; }
    }
}
