//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ARAF_OPERATOR_PANEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUCTION_OPERATOR
    {
        public int PRD_OPR_ID { get; set; }
        public Nullable<int> PROD_ID { get; set; }
        public Nullable<int> OPR_ID { get; set; }
        public Nullable<int> ROT_ID { get; set; }
        public Nullable<int> PRD_WS_ID { get; set; }
        public Nullable<int> PRD_STATUS { get; set; }
        public Nullable<int> SHIFT_ID { get; set; }
    }
}
