//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ARAF_OPERATOR_PANEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ROTATION
    {
        public int ROT_ID { get; set; }
        public Nullable<System.DateTime> ROT_START_TIME { get; set; }
        public Nullable<System.DateTime> ROT_END_TIME { get; set; }
    }
}
