//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ARAF_OPERATOR_PANEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SERVICE_LOG
    {
        public int SRVS_ID { get; set; }
        public string SRVS_NAME { get; set; }
        public string SRVS_MESSAGE { get; set; }
        public Nullable<System.DateTime> SRVS_DATE { get; set; }
        public string SRVS_PARAM { get; set; }
    }
}
