//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ARAF_OPERATOR_PANEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SHIFT
    {
        public int SHIFT_ID { get; set; }
        public string SHIFT_NO { get; set; }
        public string SHIFT_CODE { get; set; }
        public Nullable<System.DateTime> SHIFT_START_DATE { get; set; }
        public Nullable<System.DateTime> SHIFT_END_DATE { get; set; }
    }
}
