//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ARAF_OPERATOR_PANEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SUSPEND
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SUSPEND()
        {
            this.PRODUCTION_SUSPEND = new HashSet<PRODUCTION_SUSPEND>();
        }
    
        public int SUSPEND_ID { get; set; }
        public string SUSPEND_NAME { get; set; }
        public Nullable<int> SUSPEND_GROUP_ID { get; set; }
        public string SUSPEND_TYPE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PRODUCTION_SUSPEND> PRODUCTION_SUSPEND { get; set; }
    }
}
