//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ARAF_OPERATOR_PANEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYSTEM_USER_DETAIL
    {
        public int SYSUSERD_ID { get; set; }
        public int SYSUSER_ID { get; set; }
        public int FORM_ID { get; set; }
        public Nullable<bool> SYSUSERD_READ { get; set; }
        public Nullable<bool> SYSUSERD_WRITE { get; set; }
        public Nullable<bool> SYSUSERD_CHANGE { get; set; }
        public Nullable<bool> SYSUSERD_DELETE { get; set; }
    
        public virtual SYSTEM_FORMS SYSTEM_FORMS { get; set; }
        public virtual SYSTEM_USERS SYSTEM_USERS { get; set; }
    }
}
