//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ARAF_OPERATOR_PANEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYSTEM_FORMS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SYSTEM_FORMS()
        {
            this.SYSTEM_USER_DETAIL = new HashSet<SYSTEM_USER_DETAIL>();
        }
    
        public int FORM_ID { get; set; }
        public string FORM_NAME { get; set; }
        public string FORM_CAPTION { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SYSTEM_USER_DETAIL> SYSTEM_USER_DETAIL { get; set; }
    }
}
