//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ARAF_OPERATOR_PANEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYSTEM_USER_GROUPS
    {
        public int SYSUSER_GRUPID { get; set; }
        public string SYSUSERGRP_NAME { get; set; }
    }
}
