//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ARAF_OPERATOR_PANEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TMP_PLANNING
    {
        public int TMP_PLN_ID { get; set; }
        public int WS_ID { get; set; }
        public int PLAN_ID { get; set; }
        public Nullable<int> MULTIPLIER { get; set; }
        public Nullable<int> DIVIDING { get; set; }
    }
}
