//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ARAF_OPERATOR_PANEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class WORKSTATION_GROUP
    {
        public int WSG_ID { get; set; }
        public string WSG_CODE { get; set; }
        public string WSG_NAME { get; set; }
        public Nullable<int> SECTION_ID { get; set; }
    
        public virtual SECTION SECTION { get; set; }
        public virtual WORKSTATION_GROUP WORKSTATION_GROUP1 { get; set; }
        public virtual WORKSTATION_GROUP WORKSTATION_GROUP2 { get; set; }
    }
}
