//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ARAF_OPERATOR_PANEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class WORKSTATION_DETAIL
    {
        public int WSD_ID { get; set; }
        public Nullable<int> WS_ID { get; set; }
        public Nullable<int> PLC_DATA_ID { get; set; }
        public Nullable<int> WSD_COUNTER { get; set; }
        public int RESET_COUNTER { get; set; }
    }
}
